### ISSUE TITLE
Update README.md to clearly indicate Backdrop maintainer(s)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/stage_file_proxy#1]
The maintainers section of the readme does not list a clear maintainer for Backdrop. It's critical for managing security releases to know who to contact, or if the security team should manage the release on their own.

**Comment by Wylbur** [comment]
I updated the README.md doc, adding MD syntax, and adding a Current Maintainers section.  Also added myself as maintainer.  See pull request #17
