### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/stage_file_proxy#14]
I am interested in being listed as a maintainer of this module.  Let me know if that is possible

**Comment by laryn** [comment]
Ping @herbdool ☝️  -- not sure if you are technically the maintainer here or not, but since you ported it. :)

**Comment by laryn** [comment]
@Wylbur Typically the recommendation would be for you to file a PR with your name added as maintainer, so it's easy to merge it and make it official.

**Comment by herbdool** [comment]
@laryn technically I'm not. I can't recall why I didn't volunteer but I'd be happy if @Wylbur became the maintainer. Will still need a PR.

**Comment by Wylbur** [comment]
Pull request is available here: #17

**Comment by herbdool** [comment]
Thanks @Wylbur. Merged!
